name: Project Pipeline

on:
    push:
      branches:
      - main

#  Here, three jobs have been created, and their job_id values are job1_setup_environment, job2_build and job3_test.
jobs:
    job1_build_test:
        runs-on: ubuntu-latest
        steps:
            - run: echo The CI/CD is about to begin!
            - run: pwd
            # Checkout repository
            - name: Step#1- Checkout
              uses: actions/checkout@v3

            # Install python
            - name: Step#2- Setup Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'

            # Install dependencies
            - name: Step#3- Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                pip install requests
                echo "Environment is set up!"

            - name: Grant Access
              run: |
                chmod +x project/pipeline.sh
                chmod +x project/tests.sh

            - run: echo The Testing process about to begin!
            - name: Step#4-Run tests.sh
            run: |
            chmod +x ./project/tests.sh
            if ./project/tests.sh; then
            echo "Testing process completed successfully!"
            else
            echo "Testing process failed!"
            exit 1  # Or handle the failure accordingly
            fi
